load("@rules_cc//cc:defs.bzl", "cc_library")

cc_library(
    name = "Headers_preprocessors",
    hdrs = ["headers_preprocessors.h"],
    visibility = ["//visibility:public"],
)

cc_library(
    name = "PPDS_LinkedList",
    hdrs = ["PPDS_LinkedList.h"],
    visibility = ["//visibility:public"],
)


cc_library(
    name = "Util",
    hdrs = ["util.h"],
    visibility = ["//visibility:public"],
)
